---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    environment: prod
    app: mongodb
spec:
  containers:
    - name: db-server-mongodb
      imagePullPolicy: Always
      image: ramakrishnareddithi/mongodb:v1
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  selector:
    environment: prod
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---