---
apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  labels:
    environment: prod
    app: catalogue
spec:
  containers:
    - name: server-catalogue
      imagePullPolicy: Always
      image: ramakrishnareddithi/catalogue:v1
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-service
spec:
  selector:
    environment: prod
    app: catalogue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---